-- Milestone definitions based on CDC "Learn the Signs. Act Early." checklists (2022 revision).
-- Simplified Chinese titles follow CDC's official Chinese-language checklists.

INSERT INTO milestone_definition (id, age_months, category, title_en, title_zh, sort_order) VALUES
-- 2 months
('2m-social-calms', 2, 'SOCIAL', 'Calms down when spoken to or picked up', '被抱起或听到说话声时能平静下来', 1),
('2m-social-looks-face', 2, 'SOCIAL', 'Looks at your face', '注视你的脸', 2),
('2m-social-happy-to-see', 2, 'SOCIAL', 'Seems happy to see you when you walk up to them', '你走近时显得很高兴', 3),
('2m-social-smiles', 2, 'SOCIAL', 'Smiles when you talk to or smile at them', '你对宝宝说话或微笑时会报以微笑', 4),
('2m-language-sounds', 2, 'LANGUAGE', 'Makes sounds other than crying', '发出哭声以外的声音', 5),
('2m-language-reacts-sounds', 2, 'LANGUAGE', 'Reacts to loud sounds', '对巨大的声响有反应', 6),
('2m-cognitive-watches', 2, 'COGNITIVE', 'Watches you as you move', '目光跟随你的移动', 7),
('2m-cognitive-looks-toy', 2, 'COGNITIVE', 'Looks at a toy for several seconds', '注视玩具数秒', 8),
('2m-motor-head-up', 2, 'MOTOR', 'Holds head up when on tummy', '趴着时能抬头', 9),
('2m-motor-moves-limbs', 2, 'MOTOR', 'Moves both arms and both legs', '双臂和双腿都会活动', 10),
('2m-motor-opens-hands', 2, 'MOTOR', 'Opens hands briefly', '短暂张开双手', 11),

-- 4 months
('4m-social-smiles-attention', 4, 'SOCIAL', 'Smiles on their own to get your attention', '主动微笑以引起你的注意', 1),
('4m-social-chuckles', 4, 'SOCIAL', 'Chuckles (not yet a full laugh) when you try to make them laugh', '你逗宝宝时会轻声笑（还不是大笑）', 2),
('4m-social-gets-attention', 4, 'SOCIAL', 'Looks at you, moves, or makes sounds to get or keep your attention', '通过注视你、动作或发声来吸引或保持你的注意', 3),
('4m-language-coos', 4, 'LANGUAGE', 'Makes sounds like "oooo", "aahh" (cooing)', '发出"哦哦"、"啊啊"之类的声音（咿呀发声）', 4),
('4m-language-sounds-back', 4, 'LANGUAGE', 'Makes sounds back when you talk to them', '你对宝宝说话时会用声音回应', 5),
('4m-language-turns-voice', 4, 'LANGUAGE', 'Turns head toward the sound of your voice', '朝你的声音转头', 6),
('4m-cognitive-opens-mouth', 4, 'COGNITIVE', 'If hungry, opens mouth when they see breast or bottle', '饿的时候看到乳房或奶瓶会张嘴', 7),
('4m-cognitive-looks-hands', 4, 'COGNITIVE', 'Looks at their hands with interest', '饶有兴趣地看自己的手', 8),
('4m-motor-head-steady', 4, 'MOTOR', 'Holds head steady without support when you are holding them', '被抱着时不需要支撑就能稳住头部', 9),
('4m-motor-holds-toy', 4, 'MOTOR', 'Holds a toy when you put it in their hand', '把玩具放到宝宝手里时能握住', 10),
('4m-motor-swings-toys', 4, 'MOTOR', 'Uses their arm to swing at toys', '挥动手臂去够玩具', 11),
('4m-motor-hands-mouth', 4, 'MOTOR', 'Brings hands to mouth', '把手放进嘴里', 12),
('4m-motor-pushes-elbows', 4, 'MOTOR', 'Pushes up onto elbows/forearms when on tummy', '趴着时用肘部/前臂撑起身体', 13),

-- 6 months
('6m-social-knows-people', 6, 'SOCIAL', 'Knows familiar people', '认识熟悉的人', 1),
('6m-social-mirror', 6, 'SOCIAL', 'Likes to look at self in a mirror', '喜欢照镜子', 2),
('6m-social-laughs', 6, 'SOCIAL', 'Laughs', '会大笑', 3),
('6m-language-turns-sounds', 6, 'LANGUAGE', 'Takes turns making sounds with you', '和你轮流发声互动', 4),
('6m-language-raspberries', 6, 'LANGUAGE', 'Blows "raspberries" (sticks tongue out and blows)', '吐舌头吹气发出"噗噗"声', 5),
('6m-language-squeals', 6, 'LANGUAGE', 'Makes squealing noises', '发出尖叫声', 6),
('6m-cognitive-mouth-explore', 6, 'COGNITIVE', 'Puts things in their mouth to explore them', '把东西放进嘴里探索', 7),
('6m-cognitive-reaches-toy', 6, 'COGNITIVE', 'Reaches to grab a toy they want', '伸手去抓想要的玩具', 8),
('6m-cognitive-closes-lips', 6, 'COGNITIVE', 'Closes lips to show they don''t want more food', '闭上嘴唇表示不想再吃了', 9),
('6m-motor-rolls', 6, 'MOTOR', 'Rolls from tummy to back', '从趴着翻身到仰卧', 10),
('6m-motor-pushes-straight-arms', 6, 'MOTOR', 'Pushes up with straight arms when on tummy', '趴着时用手臂撑直上身', 11),
('6m-motor-leans-hands', 6, 'MOTOR', 'Leans on hands to support themselves when sitting', '坐着时用手撑地保持平衡', 12),

-- 9 months
('9m-social-strangers', 9, 'SOCIAL', 'Is shy, clingy, or fearful around strangers', '在陌生人面前害羞、粘人或害怕', 1),
('9m-social-expressions', 9, 'SOCIAL', 'Shows several facial expressions, like happy, sad, angry, and surprised', '有多种面部表情，如高兴、伤心、生气和惊讶', 2),
('9m-social-name', 9, 'SOCIAL', 'Looks when you call their name', '叫名字时会看向你', 3),
('9m-social-reacts-leave', 9, 'SOCIAL', 'Reacts when you leave (looks, reaches for you, or cries)', '你离开时有反应（注视、伸手要抱或哭）', 4),
('9m-social-peekaboo', 9, 'SOCIAL', 'Smiles or laughs when you play peek-a-boo', '玩躲猫猫时会微笑或大笑', 5),
('9m-language-mamababa', 9, 'LANGUAGE', 'Makes different sounds like "mamamama" and "babababa"', '发出"妈妈妈妈"、"爸爸爸爸"之类不同的声音', 6),
('9m-language-lifts-arms', 9, 'LANGUAGE', 'Lifts arms up to be picked up', '举起手臂要抱', 7),
('9m-cognitive-looks-dropped', 9, 'COGNITIVE', 'Looks for objects when dropped out of sight (like a spoon or toy)', '东西掉出视线时会寻找（如勺子或玩具）', 8),
('9m-cognitive-bangs', 9, 'COGNITIVE', 'Bangs two things together', '把两个东西对敲', 9),
('9m-motor-sits-self', 9, 'MOTOR', 'Gets to a sitting position by themselves', '自己坐起来', 10),
('9m-motor-transfers', 9, 'MOTOR', 'Moves things from one hand to the other hand', '把东西从一只手换到另一只手', 11),
('9m-motor-rakes', 9, 'MOTOR', 'Uses fingers to "rake" food towards themselves', '用手指把食物"耙"到自己面前', 12),
('9m-motor-sits-no-support', 9, 'MOTOR', 'Sits without support', '不用支撑能独坐', 13),

-- 12 months
('12m-social-games', 12, 'SOCIAL', 'Plays games with you, like pat-a-cake', '和你玩互动游戏，如拍手歌', 1),
('12m-language-waves', 12, 'LANGUAGE', 'Waves "bye-bye"', '挥手表示"再见"', 2),
('12m-language-mama-dada', 12, 'LANGUAGE', 'Calls a parent "mama" or "dada" or another special name', '会叫"妈妈"、"爸爸"或其他特定称呼', 3),
('12m-language-understands-no', 12, 'LANGUAGE', 'Understands "no" (pauses briefly or stops when you say it)', '听懂"不"（你说时会短暂停顿或停止）', 4),
('12m-cognitive-container', 12, 'COGNITIVE', 'Puts something in a container, like a block in a cup', '把东西放进容器里，如把积木放进杯子', 5),
('12m-cognitive-finds-hidden', 12, 'COGNITIVE', 'Looks for things they see you hide, like a toy under a blanket', '寻找看到你藏起来的东西，如毯子下的玩具', 6),
('12m-motor-pulls-stand', 12, 'MOTOR', 'Pulls up to stand', '扶着东西站起来', 7),
('12m-motor-cruises', 12, 'MOTOR', 'Walks, holding on to furniture', '扶着家具行走', 8),
('12m-motor-drinks-cup', 12, 'MOTOR', 'Drinks from a cup without a lid, as you hold it', '你扶着无盖的杯子时能用杯子喝水', 9),
('12m-motor-pincer', 12, 'MOTOR', 'Picks things up between thumb and pointer finger, like small bits of food', '用拇指和食指捏起小东西，如小块食物', 10),

-- 15 months
('15m-social-copies-children', 15, 'SOCIAL', 'Copies other children while playing, like taking toys out of a container when another child does', '玩耍时模仿其他小朋友，如跟着别的孩子把玩具从容器里拿出来', 1),
('15m-social-shows-object', 15, 'SOCIAL', 'Shows you an object they like', '把喜欢的东西拿给你看', 2),
('15m-social-claps', 15, 'SOCIAL', 'Claps when excited', '兴奋时拍手', 3),
('15m-social-hugs-toy', 15, 'SOCIAL', 'Hugs stuffed doll or other toy', '拥抱布娃娃或其他玩具', 4),
('15m-social-affection', 15, 'SOCIAL', 'Shows you affection (hugs, cuddles, or kisses you)', '向你表达爱意（拥抱、依偎或亲吻你）', 5),
('15m-language-tries-words', 15, 'LANGUAGE', 'Tries to say one or two words besides "mama" or "dada", like "ba" for ball or "da" for dog', '除"妈妈"、"爸爸"外尝试说一两个词，如用"球球"指球', 6),
('15m-language-looks-named', 15, 'LANGUAGE', 'Looks at a familiar object when you name it', '你说出熟悉物品的名称时会看向它', 7),
('15m-language-follows-gesture', 15, 'LANGUAGE', 'Follows directions given with both a gesture and words', '能听从伴随手势和语言的指令', 8),
('15m-language-points-ask', 15, 'LANGUAGE', 'Points to ask for something or to get help', '用手指指来要东西或寻求帮助', 9),
('15m-cognitive-uses-right-way', 15, 'COGNITIVE', 'Tries to use things the right way, like a phone, cup, or book', '尝试正确地使用物品，如电话、杯子或书', 10),
('15m-cognitive-stacks', 15, 'COGNITIVE', 'Stacks at least two small objects, like blocks', '至少能叠放两个小物件，如积木', 11),
('15m-motor-steps', 15, 'MOTOR', 'Takes a few steps on their own', '自己走几步', 12),
('15m-motor-finger-feeds', 15, 'MOTOR', 'Uses fingers to feed themselves some food', '用手指自己吃一些食物', 13),

-- 18 months
('18m-social-moves-away', 18, 'SOCIAL', 'Moves away from you, but looks to make sure you are close by', '会离开你身边，但会回头确认你在附近', 1),
('18m-social-points-interesting', 18, 'SOCIAL', 'Points to show you something interesting', '指给你看有趣的东西', 2),
('18m-social-hands-wash', 18, 'SOCIAL', 'Puts hands out for you to wash them', '伸出手让你帮忙洗手', 3),
('18m-social-book-pages', 18, 'SOCIAL', 'Looks at a few pages in a book with you', '和你一起看书翻几页', 4),
('18m-social-helps-dress', 18, 'SOCIAL', 'Helps you dress them by pushing arm through sleeve or lifting up foot', '配合穿衣，如把手臂伸进袖子或抬脚', 5),
('18m-language-three-words', 18, 'LANGUAGE', 'Tries to say three or more words besides "mama" or "dada"', '除"妈妈"、"爸爸"外尝试说三个或更多的词', 6),
('18m-language-one-step', 18, 'LANGUAGE', 'Follows one-step directions without any gestures, like giving you the toy when you say "Give it to me"', '不用手势也能听从一步指令，如你说"给我"时把玩具递给你', 7),
('18m-cognitive-copies-chores', 18, 'COGNITIVE', 'Copies you doing chores, like sweeping with a broom', '模仿你做家务，如用扫帚扫地', 8),
('18m-cognitive-plays-simple', 18, 'COGNITIVE', 'Plays with toys in a simple way, like pushing a toy car', '以简单的方式玩玩具，如推玩具车', 9),
('18m-motor-walks-alone', 18, 'MOTOR', 'Walks without holding on to anyone or anything', '不需要扶任何人或物就能行走', 10),
('18m-motor-scribbles', 18, 'MOTOR', 'Scribbles', '涂鸦', 11),
('18m-motor-drinks-no-lid', 18, 'MOTOR', 'Drinks from a cup without a lid and may spill sometimes', '用无盖杯子喝水（有时会洒出来）', 12),
('18m-motor-feeds-fingers', 18, 'MOTOR', 'Feeds themselves with their fingers', '用手指自己吃东西', 13),
('18m-motor-tries-spoon', 18, 'MOTOR', 'Tries to use a spoon', '尝试用勺子', 14),
('18m-motor-climbs-couch', 18, 'MOTOR', 'Climbs on and off a couch or chair without help', '不需要帮助就能爬上爬下沙发或椅子', 15),

-- 24 months
('24m-social-notices-hurt', 24, 'SOCIAL', 'Notices when others are hurt or upset, like pausing or looking sad when someone is crying', '注意到别人受伤或难过，如有人哭时会停下来或显得难过', 1),
('24m-social-looks-react', 24, 'SOCIAL', 'Looks at your face to see how to react in a new situation', '在新情况下看你的表情来决定如何反应', 2),
('24m-language-points-book', 24, 'LANGUAGE', 'Points to things in a book when you ask, like "Where is the bear?"', '你问"熊在哪里？"时会指出书中的东西', 3),
('24m-language-two-words', 24, 'LANGUAGE', 'Says at least two words together, like "More milk"', '至少会把两个词连在一起说，如"还要奶"', 4),
('24m-language-body-parts', 24, 'LANGUAGE', 'Points to at least two body parts when you ask', '你问时至少能指出两个身体部位', 5),
('24m-language-gestures', 24, 'LANGUAGE', 'Uses more gestures than just waving and pointing, like blowing a kiss or nodding yes', '会用挥手和指点以外的更多手势，如飞吻或点头', 6),
('24m-cognitive-both-hands', 24, 'COGNITIVE', 'Holds something in one hand while using the other hand, like holding a container and taking the lid off', '一只手拿东西同时用另一只手操作，如拿着容器打开盖子', 7),
('24m-cognitive-switches', 24, 'COGNITIVE', 'Tries to use switches, knobs, or buttons on a toy', '尝试使用玩具上的开关、旋钮或按钮', 8),
('24m-cognitive-multiple-toys', 24, 'COGNITIVE', 'Plays with more than one toy at the same time, like putting toy food on a toy plate', '同时玩多个玩具，如把玩具食物放在玩具盘子上', 9),
('24m-motor-kicks', 24, 'MOTOR', 'Kicks a ball', '踢球', 10),
('24m-motor-runs', 24, 'MOTOR', 'Runs', '跑步', 11),
('24m-motor-stairs', 24, 'MOTOR', 'Walks (not climbs) up a few stairs with or without help', '走上（而不是爬上）几级台阶，可有人帮助', 12),
('24m-motor-spoon', 24, 'MOTOR', 'Eats with a spoon', '用勺子吃饭', 13),

-- 30 months
('30m-social-plays-next', 30, 'SOCIAL', 'Plays next to other children and sometimes plays with them', '在其他小朋友旁边玩，有时也会一起玩', 1),
('30m-social-look-at-me', 30, 'SOCIAL', 'Shows you what they can do by saying "Look at me!"', '说"看我！"来展示自己会做的事', 2),
('30m-social-routines', 30, 'SOCIAL', 'Follows simple routines when told, like helping to pick up toys when you say "It''s clean-up time"', '按要求遵循简单的日常安排，如你说"该收拾了"时帮忙收玩具', 3),
('30m-language-fifty-words', 30, 'LANGUAGE', 'Says about 50 words', '会说大约50个词', 4),
('30m-language-action-words', 30, 'LANGUAGE', 'Says two or more words together, with one action word, like "Doggie run"', '会说两个及以上词组成的短语，其中包含动词，如"狗狗跑"', 5),
('30m-language-names-book', 30, 'LANGUAGE', 'Names things in a book when you point and ask "What is this?"', '你指着书问"这是什么？"时能说出名称', 6),
('30m-language-pronouns', 30, 'LANGUAGE', 'Says words like "I", "me", or "we"', '会说"我"、"我们"之类的词', 7),
('30m-cognitive-pretend', 30, 'COGNITIVE', 'Uses things to pretend, like feeding a block to a doll as if it were food', '用物品玩假装游戏，如把积木当食物喂娃娃', 8),
('30m-cognitive-problem-solving', 30, 'COGNITIVE', 'Shows simple problem-solving skills, like standing on a small stool to reach something', '表现出简单的解决问题能力，如站在小凳子上够东西', 9),
('30m-cognitive-two-step', 30, 'COGNITIVE', 'Follows two-step instructions, like "Put the toy down and close the door"', '能听从两步指令，如"放下玩具，关上门"', 10),
('30m-cognitive-color', 30, 'COGNITIVE', 'Shows they know at least one color, like pointing to a red crayon when you ask "Which one is red?"', '至少认识一种颜色，如你问"哪个是红色？"时指出红色蜡笔', 11),
('30m-motor-twists', 30, 'MOTOR', 'Uses hands to twist things, like turning doorknobs or unscrewing lids', '会用手扭转东西，如转门把手或拧开盖子', 12),
('30m-motor-takes-off-clothes', 30, 'MOTOR', 'Takes some clothes off by themselves, like loose pants or an open jacket', '自己脱一些衣服，如宽松的裤子或敞开的外套', 13),
('30m-motor-jumps', 30, 'MOTOR', 'Jumps off the ground with both feet', '双脚同时跳离地面', 14),
('30m-motor-turns-pages', 30, 'MOTOR', 'Turns book pages, one at a time, when you read to them', '你给宝宝读书时能一页一页地翻书', 15),

-- 36 months
('36m-social-calms', 36, 'SOCIAL', 'Calms down within 10 minutes after you leave them, like at a childcare drop-off', '你离开后（如送托时）10分钟内能平静下来', 1),
('36m-social-joins-children', 36, 'SOCIAL', 'Notices other children and joins them to play', '注意到其他小朋友并加入一起玩', 2),
('36m-language-conversation', 36, 'LANGUAGE', 'Talks with you in conversation using at least two back-and-forth exchanges', '能和你进行至少两个来回的对话', 3),
('36m-language-questions', 36, 'LANGUAGE', 'Asks "who", "what", "where", or "why" questions, like "Where is mommy?"', '会问"谁"、"什么"、"哪里"、"为什么"等问题，如"妈妈在哪里？"', 4),
('36m-language-action-picture', 36, 'LANGUAGE', 'Says what action is happening in a picture or book, like "running" or "eating"', '能说出图片或书中的动作，如"跑步"、"吃饭"', 5),
('36m-language-first-name', 36, 'LANGUAGE', 'Says first name when asked', '被问到时能说出自己的名字', 6),
('36m-language-understood', 36, 'LANGUAGE', 'Talks well enough for others to understand most of the time', '说话大部分时间能让别人听懂', 7),
('36m-cognitive-draws-circle', 36, 'COGNITIVE', 'Draws a circle when you show them how', '你示范后能画圆圈', 8),
('36m-cognitive-avoids-hot', 36, 'COGNITIVE', 'Avoids touching hot objects, like a stove, when you warn them', '你警告后会避免触碰热的东西，如炉子', 9),
('36m-motor-strings', 36, 'MOTOR', 'Strings items together, like large beads or macaroni', '能把大珠子或通心粉之类的东西串起来', 10),
('36m-motor-dresses', 36, 'MOTOR', 'Puts on some clothes by themselves, like loose pants or a jacket', '自己穿一些衣服，如宽松的裤子或外套', 11),
('36m-motor-fork', 36, 'MOTOR', 'Uses a fork', '会用叉子', 12);
